import type { StaticPropAtomicMap } from '../types'

export const sizes: StaticPropAtomicMap[] = [
  ['width', 'w'],
  ['height', 'h'],
  ['min-width', 'min-w'],
  ['min-height', 'min-h'],
  ['max-width', 'max-w'],
  ['max-height', 'max-h'],
  ['font-size', 'text'],
  ['line-height', ['leading', 'lh']],
  ['border-radius', ['rounded', 'rd']],
  ['border-top-left-radius', ['rounded-tl', 'rd-tl']],
  ['border-top-right-radius', ['rounded-tr', 'rd-tr']],
  ['border-bottom-right-radius', ['rounded-br', 'rd-br']],
  ['border-bottom-left-radius', ['rounded-bl', 'rd-bl']],
  ['border-width', ['border', 'b']],

  ['border-top-width', 'btw'],
  ['border-right-width', 'brw'],
  ['border-bottom-width', 'bbw'],
  ['border-left-width', 'blw'],
  ['border-style', 'bs'],
  ['border-top-style', 'bts'],
  ['border-right-style', 'brs'],
  ['border-bottom-style', 'bbs'],
  ['border-left-style', 'bls'],
  ['border-color', 'bc'],
  ['border-top-color', 'btc'],
  ['border-right-color', 'brc'],
  ['border-bottom-color', 'bbc'],
  ['border-left-color', 'blc'],
  ['border', 'b'],
  ['outline', 'o'],
  ['outline-width', 'ow'],
  ['outline-style', 'os'],
  ['outline-color', 'oc'],
  ['box-shadow', 'shadow'],
  ['text-shadow', 'tshadow'],
  ['letter-spacing', 'ls'],
  ['word-spacing', 'ws'],
  ['background-size', 'bg-size'],
  ['background-position', 'bg-pos'],
  ['background-repeat', 'bg-repeat'],
  ['background-attachment', 'bg-attach'],
  ['background-origin', 'bg-origin'],
  ['background-clip', 'bg-clip'],
  ['background-color', 'bgc'],
  ['background-image', 'bgi'],
  ['background-blend-mode', 'bg-blend'],
  ['background-attachment', 'bg-attach'],
  ['background-origin', 'bg-origin'],
  ['background-clip', 'bg-clip'],
  ['background-color', 'bgc'],
  ['background-image', 'bgi'],
  ['background-blend-mode', 'bg-blend'],
  ['background-attachment', 'bg-attach'],
  ['background-origin', ' bg-origin'],
]
